### ISSUE TITLE
Archival references should have a DOI

### ISSUE THREAD

**Issue by oliviaguest** [arokem/scipy-optimize#4]
There are a few references to journal articles and it seems many (all?) are not referenced with their DOI but with a hyperlink to the PDF or to the journal website (which in the case of "work by Yu and Levi" in lesson 3 leads to a 404).

**Comment by arokem** [comment]
Good catch. 

Addressed in https://github.com/arokem/scipy-optimize/commit/07341ccd4f73d941cfdb00dc86a03fc2ddcd1254 and https://github.com/arokem/scipy-optimize/commit/4a9543e214b3653d39f73c9415183e24b9777960

**Comment by oliviaguest** [comment]
I am just going to tag @labarba just in case there are any specific formatting instructions you and I should be aware of. :sweat_smile:

As far as I see this is addressed though as the hyperlinks all use a URL based on the DOI and so will resolve (much more easily) for readers.

**Comment by labarba** [comment]
As a matter of style, hyperlinked text should make sense when read, say, on a printed page, when the link is not active. So, instead of `methods see [this paper](...)`, one should write `methods, see the [paper by Smith]()`—or something such. In other words, avoid hyperlinked text like "this paper" or "here," because they don't make sense when read out.

**Comment by arokem** [comment]
Thanks! I think this should be addressed in https://github.com/arokem/scipy-optimize/commit/6c987542a0a326e477b1715eff85c5f075cda22e
